from aiogram.dispatcher.filters.state import State, StatesGroup

class BotStates(StatesGroup):
    get_client_nick = State()
    get_category = State()
    find_out_if_client_has_paid = State()
    get_sum_of_payment = State()
    ask_if_bot_should_debit_money_from_referal_account = State()
    get_number_of_days = State()
    get_message_to_send_away = State()
    get_media_to_send_away = State()
    get_video_to_send_away = State()
    get_promocode_trial_days = State()
    get_promocode_sale = State()
    get_info_whether_sale_promocode_is_endless = State()
    get_promocode_due_time = State()
    get_promocode_refer = State()
    get_promocode = State()
    get_promocode_to_delete = State()
    get_promocode_to_set_endless_sale = State()
    get_message_to_send_to_special_channel = State()
    get_category_to_edit_filter = State()
    get_stop_words_to_edit_filter = State()
    get_date_to_send_message = State()
    get_id_of_refer_to_customize_conditions = State()
    get_new_value_of_referal_condition = State()
    get_link_of_new_channel = State()
    get_id_of_new_channel = State()
    get_button_with_link_for_mailing = State()